01:03:48.400 Running build in Washington, D.C., USA (East) – iad1
01:03:48.401 Build machine configuration: 2 cores, 8 GB
01:03:48.549 Cloning github.com/hadiwritescode/portfolio-final (Branch: main, Commit: cf49fe9)
01:03:49.143 Cloning completed: 594.000ms
01:03:49.943 Restored build cache from previous deployment (4QkvdHkTmL9N7JEs7uP9AhCYDTzz)
01:03:50.750 Running "vercel build"
01:03:51.193 Vercel CLI 50.0.1
01:03:51.590 Detected `pnpm-lock.yaml` 9 which may be generated by pnpm@9.x or pnpm@10.x
01:03:51.590 Using pnpm@10.x based on project creation date
01:03:51.590 To use pnpm@9.x, manually opt in using corepack (https://vercel.com/docs/deployments/configure-a-build#corepack)
01:03:51.607 Installing dependencies...
01:03:52.346  ERR_PNPM_OUTDATED_LOCKFILE  Cannot install with "frozen-lockfile" because pnpm-lock.yaml is not up to date with <ROOT>/package.json
01:03:52.347 
01:03:52.347 Note that in CI environments this setting is true by default. If you still need to run install in such cases, use "pnpm install --no-frozen-lockfile"
01:03:52.347 
01:03:52.347   Failure reason:
01:03:52.347   specifiers in the lockfile don't match specifiers in package.json:
01:03:52.347 * 1 dependencies were added: @typescript-eslint/parser@^8.49.0
01:03:52.347 * 3 dependencies are mismatched:
01:03:52.348   - @types/node (lockfile: ^22, manifest: ^22.19.2)
01:03:52.348   - @types/react (lockfile: ^19, manifest: ^19.2.7)
01:03:52.348   - @types/react-dom (lockfile: ^19, manifest: ^19.2.3)
01:03:52.348 
01:03:52.367 Error: Command "pnpm install" exited with 1import { createClient } from "@/lib/supabase/server"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Briefcase, Settings, MessageSquare } from "lucide-react"

export default async function AdminDashboard() {
  const supabase = await createClient()

  // Fetch counts
  const [projectsResult, servicesResult, messagesResult] = await Promise.all([
    supabase.from("projects").select("id", { count: "exact", head: true }),
    supabase.from("services").select("id", { count: "exact", head: true }),
    supabase.from("contact_messages").select("id", { count: "exact", head: true }),
  ])

  const projectsCount = projectsResult.count || 0
  const servicesCount = servicesResult.count || 0
  const messagesCount = messagesResult.count || 0

  const stats = [
    {
      title: "Total Projects",
      value: projectsCount,
      icon: Briefcase,
      href: "/admin/projects",
    },
    {
      title: "Total Services",
      value: servicesCount,
      icon: Settings,
      href: "/admin/services",
    },
    {
      title: "Contact Messages",
      value: messagesCount,
      icon: MessageSquare,
      href: "/admin/messages",
    },
  ]

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold">Dashboard</h1>
        <p className="text-muted-foreground mt-2">Welcome to your admin panel</p>
      </div>

      <div className="grid gap-6 md:grid-cols-3">
        {stats.map((stat) => {
          const Icon = stat.icon
          return (
            <Card key={stat.title}>
              <CardHeader className="flex flex-row items-center justify-between pb-2">
                <CardTitle className="text-sm font-medium">{stat.title}</CardTitle>
                <Icon className="h-4 w-4 text-muted-foreground" />
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold">{stat.value}</div>
              </CardContent>
            </Card>
          )
        })}
      </div>
    </div>
  )
}
